# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d47fa4e6e7c3f6cf3554d3fe5dd0b05739f080b73d2d6432aa7e631ee44f14bcf43314f929f7d608ecd7bee697d328b08157a48fd2c95d178e38673986d992e

test:
  secret_key_base: 31e594afd64543c083d4ffaeb94da2496de69f1dbc0abd88138b271055ebf0fcc8eddb03d6773d20e741cbd300384b52899edc5af304c52ac45e4fe019d8670f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
